### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by aaronjpitts** [beautifulBoys/webpack-replace-loader#2]
Hi, I'm trying to replace all occurances of `data-accordion` with `v-accordion data-accordion` with the below but I just can't seem to get it to replace. Many other things I've tried have just given errors. I only want to match `data-accordion` not `data-accordion-item` for example.

Thanks

```
{
      test: /\.js$|\.vue$/,
      loader: 'webpack-replace-loader',
      options: {
        arr: [
          { search: /data-accordion(?!-)/, replace: 'v-accordion data-accordion', attr: 'g' }
        ]
      }
    }
```

**Comment by beautifulBoys** [comment]
Your problem is about regular expressions, not the loader. you can try to write a regular expressions rule exclude "-item".

You can also solve the problem by way of skill. Try this:
```
     {
        test: /test\.html$/,
        loader: 'webpack-replace-loader',
        options: {
          arr: [
            { search: 'data-accordion', replace: 'v-accordion data-accordion', attr: 'g' },
            { search: 'v-accordion data-accordion-item', replace: 'data-accordion-item', attr: 'g' }
          ]
        }
      }
```

Above, thank you!

**Comment by beautifulBoys** [comment]
![git](https://user-images.githubusercontent.com/24930325/36013862-a3bf62d8-0da1-11e8-8c4b-ddb4581e27ed.png)

about this.
